### ISSUE TITLE
Is there a reason why you are using different colour codes in your CSS?

### ISSUE THREAD

**Issue by hannahgooding** [halimahexe/FAC-Website#3]
https://github.com/halimahexe/FAC-Website/blob/31af3e685d6a3dca72eb75e995dc5e809f646a74/style.css#L18
e.g. hex / rgb / hsl

**Comment by halimahexe** [comment]
I was playing around with different ways to code colours but appreciate this is a bit messy, so I've refactored :)

**Comment by hannahgooding** [comment]
That makes sense! It was more a question to understand if one made more sense in your brain over another. But yes, consistency is good ☺️
