### ISSUE TITLE
Refactor the min/max button logic to reduce extra loops

### ISSUE THREAD

**Issue by hannahgooding** [halimahexe/FAC-Website#6]
I don't think you need these match functions

https://github.com/halimahexe/FAC-Website/blob/31af3e685d6a3dca72eb75e995dc5e809f646a74/script.js#L19-L24

You have the number so you can just get the elements by id directly using template literal strings i.e something like

```javascript
const nonMenu = document.querySelector(`#non-menu-${number}`)
nonMenu.classList.add('hidden');
```

**Comment by halimahexe** [comment]
Aha, that's a really good point! I think I had tried to use template literals for something else previously that didn't quite work and didn't think to try again. Thank you!
